// SPDX-FileCopyrightText: 2024 Brandon Li <48413902+aspiringLich@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Utility;
using Robust.Shared.Maths;
using Robust.Client.Graphics;
using System.Numerics;
namespace Content.Client.Communications.UI;

[GenerateTypedNameReferences]
public sealed partial class AlertLevelButton : Control
{

    public Action<string>? OnPressedAlertButton;
    public readonly string alertLevel;
    public bool Disabled {
        get => AlertButton.Disabled;
        set {
            AlertButton.Disabled = value;
            UpdateDisabled();
        }
    }

    public string? ToolTip
    {
        get => AlertButton.ToolTip;
        set => AlertButton.ToolTip = value;
    }

    public readonly Color color;
    public readonly Color colorToBlend = Color.FromHsl(new Vector4(0.0f, 0.0f, 0.3f, 1.0f));
    public readonly Color disabledColor;

    public AlertLevelButton(string alertLevel, Color color)
    {
        RobustXamlLoader.Load(this);
        this.color = color;


        disabledColor = Color.Blend(color, colorToBlend, Color.BlendFactor.Zero, Color.BlendFactor.DstColor);

        this.alertLevel = alertLevel;

        AlertButton.ModulateSelfOverride = color;
        AlertButton.OnPressed += _ => OnPressedAlertButton?.Invoke(alertLevel);
    }

    private void UpdateDisabled()
    {
        // invertido pq o botão acionado precisa ignorar inputs
        if (this.Disabled) AlertButton.ModulateSelfOverride = color;
        else AlertButton.ModulateSelfOverride = disabledColor;
    }
}
